//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _13_WebService.ServiceReference4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/BMIcal", ReplyAction="http://tempuri.org/IService2/BMIcalResponse")]
        double BMIcal(double weigh, double height);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/BMIcal", ReplyAction="http://tempuri.org/IService2/BMIcalResponse")]
        System.Threading.Tasks.Task<double> BMIcalAsync(double weigh, double height);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : _13_WebService.ServiceReference4.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<_13_WebService.ServiceReference4.IService2>, _13_WebService.ServiceReference4.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double BMIcal(double weigh, double height) {
            return base.Channel.BMIcal(weigh, height);
        }
        
        public System.Threading.Tasks.Task<double> BMIcalAsync(double weigh, double height) {
            return base.Channel.BMIcalAsync(weigh, height);
        }
    }
}
