//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _13_WebService.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.WebService2Soap")]
    public interface WebService2Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateCompoundInterest", ReplyAction="*")]
        double CalculateCompoundInterest(double principal, double rate, int timesCompounded, int years);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateCompoundInterest", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CalculateCompoundInterestAsync(double principal, double rate, int timesCompounded, int years);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2SoapChannel : _13_WebService.ServiceReference2.WebService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2SoapClient : System.ServiceModel.ClientBase<_13_WebService.ServiceReference2.WebService2Soap>, _13_WebService.ServiceReference2.WebService2Soap {
        
        public WebService2SoapClient() {
        }
        
        public WebService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalculateCompoundInterest(double principal, double rate, int timesCompounded, int years) {
            return base.Channel.CalculateCompoundInterest(principal, rate, timesCompounded, years);
        }
        
        public System.Threading.Tasks.Task<double> CalculateCompoundInterestAsync(double principal, double rate, int timesCompounded, int years) {
            return base.Channel.CalculateCompoundInterestAsync(principal, rate, timesCompounded, years);
        }
    }
}
